name: py_env
channels:
  - conda-forge
  - defaults
  - bashtage
  - delichon
dependencies:
  - python
  - pandas
  - pytest
  - pytest-cov
  - numpy
  - nbconvert
  - nbformat
  - pandas_datareader
  - statsmodels
  - scipy
  - arch
  - matplotlib
  - requests
  - beautifulsoup4
  - scikit-learn
  - openpyxl
  - jupyter
  - pypyodbc
  - dash==0.30.0
  - dash-core-components==0.38.0
  - dash-html-components==0.13.2
  - dash-renderer==0.15.1
  - flask=0.11.1
  - flask-cors=2.1.2
  - scikit-image=0.12.3
  - keras==2.2.4
  - keras-applications==1.0.6
  - keras-preprocessing==1.0.5
  - plotly==3.4.1
  - pyodbc==4.0.24
  - seaborn==0.9.0
  - tensorboard==1.12.0
  - tensorflow==1.12.0
  - termcolor==1.1.0
# R packages.
  - r-base=3.4.1
  - r-dt
  - r-ggfortify
  - r-ggplot2
  - r-gsw
  - r-httr
  - r-irkernel
  - r-lubridate
  - r-mapdata
  - r-ncdf4
  - r-oce
  - r-rcolorbrewer
  - r-rerddap
  - r-reshape2
  - r-sp
  - r-xtractomatic
  - r-xts
