name: my_environment
channels:
  - conda-forge
  - defaults
  - bashtage
  - delichon
dependencies:
  - python
  - pandas
  - pytest
  - pytest-cov
  - numpy
  - nbconvert
  - nbformat
  - pandas_datareader
  - statsmodels
  - scipy
  - arch
  - matplotlib
  - requests
  - beautifulsoup4
  - scikit-learn
