model_features = {
    # General
    # 'Unformatted_API_UWI_14': {'dtype': str, 'ftype': 'uid'},
    # 'FirstProdDate': {'dtype': str, 'ftype': 'general'},
    # 'ModernCompletion': {'dtype': int, 'ftype': 'general'},
    #     'Formation': { 'dtype': str, 'ftype': 'general' },
    'RSInterval': {'dtype': str, 'ftype': 'general'},
    # 'Latitude': {'dtype': float, 'ftype': 'general'},
    # 'Longitude': {'dtype': float, 'ftype': 'general'},
    # 'Latitude_BH': {'dtype': float, 'ftype': 'general'},
    # 'Longitude_BH': {'dtype': float, 'ftype': 'general'},
    # 'BHL_Y': {'dtype': float, 'ftype': 'general'},
    # 'BHL_X': {'dtype': float, 'ftype': 'general'},
    # 'CompletionNumber': {'dtype': int, 'ftype': 'general'},

    # Geologic
    'Isopach_FT': {'dtype': float, 'ftype': 'geologic'},
    'EffectivePorosity_PCT': {'dtype': float, 'ftype': 'geologic'},
    'WaterSaturation_PCT': {'dtype': float, 'ftype': 'geologic'},
    'ClayVolume_PCT': {'dtype': float, 'ftype': 'geologic'},
    'TotalOrganicCarbon_WTPCT': {'dtype': float, 'ftype': 'geologic'},
    'GammaRay_API': {'dtype': float, 'ftype': 'geologic'},
    # 'Resistivity_OHMSM': {'dtype': float, 'ftype': 'geologic'},
    # 'PhiH_FT': {'dtype': float, 'ftype': 'geologic'},
    'HCPV_PCT': {'dtype': float, 'ftype': 'geologic'},
    # 'HeightOfHCPV_FT': {'dtype': float, 'ftype': 'geologic'},
    'TopOfZone_FT': {'dtype': float, 'ftype': 'geologic'},
    # 'BottomOfZone_FT': {'dtype': float, 'ftype': 'geologic'},
    # 'TrueVerticalDepth_FT': {'dtype': float, 'ftype': 'geologic'},
    'GOR': {'dtype': float, 'ftype': 'geologic'},
    'WOR': {'dtype': float, 'ftype': 'geologic'},

    # Engineering
    'LateralLength_FT': {'dtype': float, 'ftype': 'engineering'},
    'AverageStageSpacing_FT': {'dtype': float, 'ftype': 'engineering'},
    'FracStages': {'dtype': float, 'ftype': 'engineering'},
    # 'RSFracJobType': {'dtype': str, 'ftype': 'engineering'},
    # 'RSProppantType': {'dtype': str, 'ftype': 'engineering'},
    'ProppantIntensity_LBSPerFT': {'dtype': float, 'ftype': 'engineering'},
    # 'ProppantLoading_LBSPerGAL': {'dtype': float, 'ftype': 'engineering'},
    'FluidIntensity_BBLPerFT': {'dtype': float, 'ftype': 'engineering'},
    # 'WaterIntensity_GALPerFT': {'dtype': float, 'ftype': 'engineering'},
    # 'ChokeSize_64IN': {'dtype': float, 'ftype': 'engineering'},
    'AvgHzDistSameZone_FT': {'dtype': float, 'ftype': 'engineering'},
    'AvgHzDistAnyZone_FT': {'dtype': float, 'ftype': 'engineering'},

    # Production -- Oil
    'Prod30DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod60DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod90DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod180DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod360DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod720DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod1080DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

#     'Prod30DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod60DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod90DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod180DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod360DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod720DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod1080DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

    # 'Prod30DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod60DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod90DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod180DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod360DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod720DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod1080DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

    # 'Prod30DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod60DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod90DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod180DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod360DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod720DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod1080DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

    # 'Prod30DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod60DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod90DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod180DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod360DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod720DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod1080DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

    # Production -- gas
    'Prod30DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod60DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod90DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod180DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod360DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod720DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod1080DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},

    # Production -- water
    'Prod30DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod60DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod90DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod180DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod360DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod720DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod1080DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
}

model_features_MC = {
    # General
    # 'Unformatted_API_UWI_14': {'dtype': str, 'ftype': 'uid'},
    # 'FirstProdDate': {'dtype': str, 'ftype': 'general'},
    # 'ModernCompletion': {'dtype': int, 'ftype': 'general'},
    #     'Formation': { 'dtype': str, 'ftype': 'general' },
    'RSInterval': {'dtype': str, 'ftype': 'general'},
    # 'Latitude': {'dtype': float, 'ftype': 'general'},
    # 'Longitude': {'dtype': float, 'ftype': 'general'},
    # 'Latitude_BH': {'dtype': float, 'ftype': 'general'},
    # 'Longitude_BH': {'dtype': float, 'ftype': 'general'},
    # 'BHL_Y': {'dtype': float, 'ftype': 'general'},
    # 'BHL_X': {'dtype': float, 'ftype': 'general'},
    # 'CompletionNumber': {'dtype': int, 'ftype': 'general'},

    # Geologic
    'Isopach_FT': {'dtype': float, 'ftype': 'geologic'},
    'EffectivePorosity_PCT': {'dtype': float, 'ftype': 'geologic'},
    'WaterSaturation_PCT': {'dtype': float, 'ftype': 'geologic'},
    'ClayVolume_PCT': {'dtype': float, 'ftype': 'geologic'},
    'TotalOrganicCarbon_WTPCT': {'dtype': float, 'ftype': 'geologic'},
    'GammaRay_API': {'dtype': float, 'ftype': 'geologic'},
    # 'Resistivity_OHMSM': {'dtype': float, 'ftype': 'geologic'},
    # 'PhiH_FT': {'dtype': float, 'ftype': 'geologic'},
    'HCPV_PCT': {'dtype': float, 'ftype': 'geologic'},
    # 'HeightOfHCPV_FT': {'dtype': float, 'ftype': 'geologic'},
    'TopOfZone_FT': {'dtype': float, 'ftype': 'geologic'},
    'BottomOfZone_FT': {'dtype': float, 'ftype': 'geologic'},
    # 'TrueVerticalDepth_FT': {'dtype': float, 'ftype': 'geologic'},
    # 'GOR': {'dtype': float, 'ftype': 'geologic'},
    # 'WOR': {'dtype': float, 'ftype': 'geologic'},
    'WHLiquids_PCT': {'dtype': float, 'ftype': 'geologic'},

    # Engineering
    'LateralLength_FT': {'dtype': float, 'ftype': 'engineering'},
    'AverageStageSpacing_FT': {'dtype': float, 'ftype': 'engineering'},
    'FracStages': {'dtype': float, 'ftype': 'engineering'},
    # 'RSFracJobType': {'dtype': str, 'ftype': 'engineering'},
    # 'RSProppantType': {'dtype': str, 'ftype': 'engineering'},
    'ProppantIntensity_LBSPerFT': {'dtype': float, 'ftype': 'engineering'},
    # 'ProppantLoading_LBSPerGAL': {'dtype': float, 'ftype': 'engineering'},
    'FluidIntensity_BBLPerFT': {'dtype': float, 'ftype': 'engineering'},
    # 'WaterIntensity_GALPerFT': {'dtype': float, 'ftype': 'engineering'},
    # 'ChokeSize_64IN': {'dtype': float, 'ftype': 'engineering'},
    'AvgHzDistSameZone_FT': {'dtype': float, 'ftype': 'engineering'},
    'AvgHzDistAnyZone_FT': {'dtype': float, 'ftype': 'engineering'},

    # Production -- Oil
    'Prod30DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod60DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod90DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod180DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod360DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod720DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod1080DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

#     'Prod30DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod60DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod90DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod180DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod360DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod720DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod1080DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

    # 'Prod30DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod60DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod90DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod180DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod360DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod720DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod1080DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

    # 'Prod30DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod60DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod90DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod180DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod360DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod720DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod1080DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

    # 'Prod30DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod60DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod90DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod180DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod360DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod720DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod1080DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

    # Production -- gas
    'Prod30DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod60DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod90DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod180DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod360DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod720DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod1080DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},

    # Production -- water
    'Prod30DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod60DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod90DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod180DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod360DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod720DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod1080DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
}

model_features_Utica = {
    # General
    # 'Unformatted_API_UWI_14': {'dtype': str, 'ftype': 'uid'},
    # 'FirstProdDate': {'dtype': str, 'ftype': 'general'},
    # 'ModernCompletion': {'dtype': int, 'ftype': 'general'},
    #     'Formation': { 'dtype': str, 'ftype': 'general' },
    'RSInterval': {'dtype': str, 'ftype': 'general'},
    # 'Latitude': {'dtype': float, 'ftype': 'general'},
    # 'Longitude': {'dtype': float, 'ftype': 'general'},
    # 'Latitude_BH': {'dtype': float, 'ftype': 'general'},
    # 'Longitude_BH': {'dtype': float, 'ftype': 'general'},
    # 'BHL_Y': {'dtype': float, 'ftype': 'general'},
    # 'BHL_X': {'dtype': float, 'ftype': 'general'},
    # 'CompletionNumber': {'dtype': int, 'ftype': 'general'},

    # Geologic
    # 'Isopach_FT': {'dtype': float, 'ftype': 'geologic'},
    # 'EffectivePorosity_PCT': {'dtype': float, 'ftype': 'geologic'},
    # 'WaterSaturation_PCT': {'dtype': float, 'ftype': 'geologic'},
    # 'ClayVolume_PCT': {'dtype': float, 'ftype': 'geologic'},
    # 'TotalOrganicCarbon_WTPCT': {'dtype': float, 'ftype': 'geologic'},
    'GammaRay_API': {'dtype': float, 'ftype': 'geologic'},
    # 'Resistivity_OHMSM': {'dtype': float, 'ftype': 'geologic'},
    'PhiH_FT': {'dtype': float, 'ftype': 'geologic'},
    'HCPV_PCT': {'dtype': float, 'ftype': 'geologic'},
    'HeightOfHCPV_FT': {'dtype': float, 'ftype': 'geologic'},
    'TopOfZone_FT': {'dtype': float, 'ftype': 'geologic'},
    'BottomOfZone_FT': {'dtype': float, 'ftype': 'geologic'},
    # 'TrueVerticalDepth_FT': {'dtype': float, 'ftype': 'geologic'},
    # 'GOR': {'dtype': float, 'ftype': 'geologic'},
    # 'WOR': {'dtype': float, 'ftype': 'geologic'},
    'WHLiquids_PCT': {'dtype': float, 'ftype': 'geologic'},
    'BCF per section / ft': {'dtype': float, 'ftype': 'geologic'},
    'BCF per section': {'dtype': float, 'ftype': 'geologic'},
    'Pressure (MMpsi)': {'dtype': float, 'ftype': 'geologic'},
    'Water Saturation (Euc)': {'dtype': float, 'ftype': 'geologic'},
    'Resistivity(OHMSM)': {'dtype': float, 'ftype': 'geologic'},
    'ClayVolume (pct)': {'dtype': float, 'ftype': 'geologic'},
    'Thickness (ft)': {'dtype': float, 'ftype': 'geologic'},
    'bulkdensity (g/cm3)': {'dtype': float, 'ftype': 'geologic'},
    'TotalPorosity (Euc)': {'dtype': float, 'ftype': 'geologic'},
    'TotalOrganicCarbon': {'dtype': float, 'ftype': 'geologic'},
    'NeutronPorosity': {'dtype': float, 'ftype': 'geologic'},

    # Engineering
    'LateralLength_FT': {'dtype': float, 'ftype': 'engineering'},
    'AverageStageSpacing_FT': {'dtype': float, 'ftype': 'engineering'},
    'FracStages': {'dtype': float, 'ftype': 'engineering'},
    # 'RSFracJobType': {'dtype': str, 'ftype': 'engineering'},
    # 'RSProppantType': {'dtype': str, 'ftype': 'engineering'},
    'ProppantIntensity_LBSPerFT': {'dtype': float, 'ftype': 'engineering'},
    # 'ProppantLoading_LBSPerGAL': {'dtype': float, 'ftype': 'engineering'},
    'FluidIntensity_BBLPerFT': {'dtype': float, 'ftype': 'engineering'},
    # 'WaterIntensity_GALPerFT': {'dtype': float, 'ftype': 'engineering'},
    # 'ChokeSize_64IN': {'dtype': float, 'ftype': 'engineering'},
    'AvgHzDistSameZone_FT': {'dtype': float, 'ftype': 'engineering'},
    'AvgHzDistAnyZone_FT': {'dtype': float, 'ftype': 'engineering'},
    'Proppant_LBS': {'dtype': float, 'ftype': 'engineering'},
    'TotalFluidPumped_BBL': {'dtype': float, 'ftype': 'engineering'},


    # Production -- Oil
    'Prod30DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod60DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod90DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod180DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod360DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod720DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod1080DaysOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

#     'Prod30DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod60DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod90DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod180DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod360DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod720DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
#     'Prod1080DaysDiffOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

    # 'Prod30DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod60DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod90DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod180DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod360DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod720DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod1080DaysDiffSqrtOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

    # 'Prod30DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod60DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod90DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod180DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod360DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod720DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod1080DaysDiffLogOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

    # 'Prod30DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod60DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod90DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod180DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod360DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod720DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},
    # 'Prod1080DaysRatioOil_BBL_rs': {'dtype': float, 'ftype': 'production'},

    # Production -- gas
    'Prod30DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod60DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod90DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod180DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod360DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod720DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},
    'Prod1080DaysGas_MCF_rs': {'dtype': float, 'ftype': 'production'},

    # Production -- water
    'Prod30DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod60DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod90DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod180DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod360DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod720DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
    'Prod1080DaysWtr_BBL_rs': {'dtype': float, 'ftype': 'production'},
}